### ISSUE TITLE
Pád programu - prázdny riadok

### ISSUE THREAD

**Issue by zoszv1** [duskyme/Communication-Markem-Imaje-9450-94xx#7]
Program spadne po načítaní tabuľky a vybratí riadku/riadkov, ktorý je oddelený prázdnym riadkom.
[test1.xls](https://github.com/duskyme/Communication-Markem-Imaje-9450-94xx/files/10870647/test1.xls)

**Comment by duskyme** [comment]
spôsobené, že sú v bunkách hodnoty null!
