### ISSUE TITLE
Nezobrazovanie dát

### ISSUE THREAD

**Issue by zoszv1** [duskyme/Communication-Markem-Imaje-9450-94xx#8]
Nezobrazia sa dáta z tabuľky, ak v prvom riadku daného stĺpca je prázdna bunka.
[test2.xls](https://github.com/duskyme/Communication-Markem-Imaje-9450-94xx/files/10870692/test2.xls)

**Comment by duskyme** [comment]
Program bol vytváraný podľa predlohy, ktorú ste poskytli. Podľa predlohy máte v prvom riadku hlavičku. táto hlavička sa používala na identifikovanie počtu stĺpcov. Keďže uvedený príklad neobsahuje hlavičku, tak to potom spôsobuje problémy. Takže moja otázka znie, budeme sa držať toho, čo ste poskytli na začiatku, alebo s tým budeme robiť pokusy??

**Comment by zoszv1** [comment]
Áno, s predlohou pre zväzky vodičov a káblov tento problém nenastáva. Avšak predloha podobná tej hore (test2.xls) vznikla až po vašom zjednodušení, že dlhé texty (bužírky) sa nebudú otvárať cez "Tlač textu", ale cez "Tlač z databázy" keďže už obsahuje možnosť otvoriť súbor. 
A znovu... nejedná sa o závažnú chybu, bez ktorej nie je možné existovať (viď. https://github.com/duskyme/Communication-Markem-Imaje-9450-94xx/issues/9#issuecomment-1453065750).
