### ISSUE TITLE
Zmena dát v náhľade

### ISSUE THREAD

**Issue by zoszv1** [duskyme/Communication-Markem-Imaje-9450-94xx#9]
Pri zmene výberu stĺpcov, ktoré majú byť odosielané, sa nezmenia dáta zobrazované v náhľade. Nezmenia sa ani pri opätovnom kliknutí na riadok. Pomôže až preklik na iný riadok a späť na pôvodný.

**Comment by duskyme** [comment]
Ešte raz pripomínam, kód je otvorený. Takéto "neuveriteľne závažné chyby, ktoré sú teda naozaj cez čiaru a neuveriteľne zdržujú" si dokážeme spraviť aj sami....či?

**Comment by zoszv1** [comment]
Ak dobre vidím, nikde som nenapísal o "neuveriteľne závažnej chybe/zdržovaniu". Narazil som na neštandardné/nelogické správanie programu, tak som vytvoril "issue". Ak by som to vedel spraviť a mal na to čas, tak to spravím, ale to momentálne nemám. Aj to je dôvod vytvárania takýchto poznámok/zoznamov...
